program: train.py
name: sweepdemo
project: mlops_final_exercise
entity: MichaelFN
metric:
    goal: minimize
    name: validation_loss
parameters:
    learning_rate:
        min: 0.00001
        max: 0.01
        distribution: log_uniform
    batch_size:
        values: [16, 32, 64]
    epochs:
        values: [5, 10, 15]
run_cap: 10